# Generated by Django 2.2.5 on 2019-10-02 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('delivery_addr', models.CharField(blank=True, default='', max_length=200)),
                ('contact_info', models.TextField()),
                ('status', models.TextField(default='Não finalizado')),
                ('announcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_demand', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
