# Generated by Django 2.2.5 on 2019-09-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartsDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('delivery_addr', models.CharField(blank=True, default='', max_length=200)),
                ('contact_info', models.TextField()),
                ('announcer', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
