# Generated by Django 2.2.5 on 2019-10-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_demand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsdemand',
            name='status',
            field=models.CharField(choices=[('YES', 'Finalizado'), ('NO', 'Não Finalizado')], max_length=500),
        ),
    ]
