# Generated by Django 2.2.5 on 2019-10-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_demand', '0002_auto_20191003_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsdemand',
            name='status',
            field=models.CharField(choices=[('Finalizado', 'YES'), ('Não Finalizado', 'NO')], max_length=500),
        ),
    ]
