# Generated by Django 2.2.5 on 2019-10-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_demand', '0005_auto_20191003_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsdemand',
            name='status',
            field=models.CharField(choices=[('Não Finalizado', 'Não Finalizado'), ('Finalizado', 'Finalizado')], max_length=500),
        ),
    ]
