# Generated by Django 2.2.5 on 2019-10-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts_demand', '0006_auto_20191003_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partsdemand',
            options={'ordering': ['conclusion_status']},
        ),
        migrations.RemoveField(
            model_name='partsdemand',
            name='status',
        ),
        migrations.AddField(
            model_name='partsdemand',
            name='conclusion_status',
            field=models.BooleanField(default=False),
        ),
    ]
